// Generated by Supabase (generate_typescript_types) for project zzbbniffrdigluisvxxb after migrations 0001–0005.
// Do not edit by hand; regenerate after every schema change.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      accounts: {
        Row: {
          currency: string
          color: string | null
          created_at: string
          household_id: string
          icon: string | null
          id: string
          is_archived: boolean
          name_ar: string | null
          name_en: string | null
          opening_balance: number
          sort_order: number
          type: Database["public"]["Enums"]["account_type"]
          updated_at: string
        }
        Insert: {
          currency?: string
          color?: string | null
          created_at?: string
          household_id: string
          icon?: string | null
          id?: string
          is_archived?: boolean
          name_ar?: string | null
          name_en?: string | null
          opening_balance?: number
          sort_order?: number
          type?: Database["public"]["Enums"]["account_type"]
          updated_at?: string
        }
        Update: {
          currency?: string
          color?: string | null
          created_at?: string
          household_id?: string
          icon?: string | null
          id?: string
          is_archived?: boolean
          name_ar?: string | null
          name_en?: string | null
          opening_balance?: number
          sort_order?: number
          type?: Database["public"]["Enums"]["account_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "accounts_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      budgets: {
        Row: {
          amount: number
          category_id: string
          created_at: string
          household_id: string
          id: string
          is_archived: boolean
          is_starter: boolean
          subcategory_id: string | null
          updated_at: string
        }
        Insert: {
          amount: number
          category_id: string
          created_at?: string
          household_id: string
          id?: string
          is_archived?: boolean
          is_starter?: boolean
          subcategory_id?: string | null
          updated_at?: string
        }
        Update: {
          amount?: number
          category_id?: string
          created_at?: string
          household_id?: string
          id?: string
          is_archived?: boolean
          is_starter?: boolean
          subcategory_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "budgets_household_id_category_id_fkey"
            columns: ["household_id", "category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["household_id", "id"]
          },
          {
            foreignKeyName: "budgets_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "budgets_household_id_subcategory_id_fkey"
            columns: ["household_id", "subcategory_id"]
            isOneToOne: false
            referencedRelation: "subcategories"
            referencedColumns: ["household_id", "id"]
          },
        ]
      }
      categories: {
        Row: {
          color: string | null
          created_at: string
          household_id: string
          icon: string | null
          id: string
          is_archived: boolean
          kind: Database["public"]["Enums"]["category_kind"]
          name_ar: string | null
          name_en: string | null
          sort_order: number
          updated_at: string
        }
        Insert: {
          color?: string | null
          created_at?: string
          household_id: string
          icon?: string | null
          id?: string
          is_archived?: boolean
          kind: Database["public"]["Enums"]["category_kind"]
          name_ar?: string | null
          name_en?: string | null
          sort_order?: number
          updated_at?: string
        }
        Update: {
          color?: string | null
          created_at?: string
          household_id?: string
          icon?: string | null
          id?: string
          is_archived?: boolean
          kind?: Database["public"]["Enums"]["category_kind"]
          name_ar?: string | null
          name_en?: string | null
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      heartbeat: {
        Row: {
          id: number
          pinged_at: string
        }
        Insert: {
          id?: number
          pinged_at?: string
        }
        Update: {
          id?: number
          pinged_at?: string
        }
        Relationships: []
      }
      family_invites: {
        Row: {
          created_at: string
          decided_at: string | null
          email: string
          friend_name: string
          household_id: string
          id: string
          invited_by: string | null
          status: string
        }
        Insert: {
          created_at?: string
          decided_at?: string | null
          email: string
          friend_name: string
          household_id: string
          id?: string
          invited_by?: string | null
          status?: string
        }
        Update: {
          created_at?: string
          decided_at?: string | null
          email?: string
          friend_name?: string
          household_id?: string
          id?: string
          invited_by?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "family_invites_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      household_members: {
        Row: {
          created_at: string
          display_name: string
          household_id: string
          locale: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          display_name: string
          household_id: string
          locale?: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string
          display_name?: string
          household_id?: string
          locale?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "household_members_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      households: {
        Row: {
          currencies: string[]
          status: string
          has_sample_data: boolean
          sample_cleared_at: string | null
          created_at: string
          currency: string
          id: string
          name: string
        }
        Insert: {
          currencies?: string[]
          status?: string
          has_sample_data?: boolean
          sample_cleared_at?: string | null
          created_at?: string
          currency?: string
          id?: string
          name: string
        }
        Update: {
          currencies?: string[]
          status?: string
          has_sample_data?: boolean
          sample_cleared_at?: string | null
          created_at?: string
          currency?: string
          id?: string
          name?: string
        }
        Relationships: []
      }
      items: {
        Row: {
          created_at: string
          household_id: string
          id: string
          is_archived: boolean
          name_ar: string | null
          name_en: string | null
          sort_order: number
          subcategory_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          household_id: string
          id?: string
          is_archived?: boolean
          name_ar?: string | null
          name_en?: string | null
          sort_order?: number
          subcategory_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          household_id?: string
          id?: string
          is_archived?: boolean
          name_ar?: string | null
          name_en?: string | null
          sort_order?: number
          subcategory_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "items_household_id_subcategory_id_fkey"
            columns: ["household_id", "subcategory_id"]
            isOneToOne: false
            referencedRelation: "subcategories"
            referencedColumns: ["household_id", "id"]
          },
        ]
      }
      subcategories: {
        Row: {
          category_id: string
          created_at: string
          household_id: string
          id: string
          is_archived: boolean
          name_ar: string | null
          name_en: string | null
          sort_order: number
          updated_at: string
        }
        Insert: {
          category_id: string
          created_at?: string
          household_id: string
          id?: string
          is_archived?: boolean
          name_ar?: string | null
          name_en?: string | null
          sort_order?: number
          updated_at?: string
        }
        Update: {
          category_id?: string
          created_at?: string
          household_id?: string
          id?: string
          is_archived?: boolean
          name_ar?: string | null
          name_en?: string | null
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "subcategories_household_id_category_id_fkey"
            columns: ["household_id", "category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["household_id", "id"]
          },
        ]
      }
      transactions: {
        Row: {
          to_amount: number | null
          account_id: string
          amount: number
          created_at: string
          created_by: string | null
          deleted_at: string | null
          household_id: string
          id: string
          item_id: string | null
          note: string | null
          occurred_on: string
          photo_path: string | null
          is_sample: boolean
          to_account_id: string | null
          type: Database["public"]["Enums"]["txn_type"]
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          to_amount?: number | null
          account_id: string
          amount: number
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          household_id: string
          id?: string
          item_id?: string | null
          note?: string | null
          occurred_on?: string
          photo_path?: string | null
          is_sample?: boolean
          to_account_id?: string | null
          type: Database["public"]["Enums"]["txn_type"]
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          to_amount?: number | null
          account_id?: string
          amount?: number
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          household_id?: string
          id?: string
          item_id?: string | null
          note?: string | null
          occurred_on?: string
          photo_path?: string | null
          is_sample?: boolean
          to_account_id?: string | null
          type?: Database["public"]["Enums"]["txn_type"]
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_household_id_account_id_fkey"
            columns: ["household_id", "account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["household_id", "id"]
          },
          {
            foreignKeyName: "transactions_household_id_account_id_fkey"
            columns: ["household_id", "account_id"]
            isOneToOne: false
            referencedRelation: "v_account_balances"
            referencedColumns: ["household_id", "account_id"]
          },
          {
            foreignKeyName: "transactions_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_household_id_item_id_fkey"
            columns: ["household_id", "item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["household_id", "id"]
          },
          {
            foreignKeyName: "transactions_household_id_to_account_id_fkey"
            columns: ["household_id", "to_account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["household_id", "id"]
          },
          {
            foreignKeyName: "transactions_household_id_to_account_id_fkey"
            columns: ["household_id", "to_account_id"]
            isOneToOne: false
            referencedRelation: "v_account_balances"
            referencedColumns: ["household_id", "account_id"]
          },
        ]
      }
    }
    Views: {
      v_account_balances: {
        Row: {
          currency: string | null
          account_id: string | null
          balance: number | null
          color: string | null
          household_id: string | null
          icon: string | null
          is_archived: boolean | null
          name_ar: string | null
          name_en: string | null
          type: Database["public"]["Enums"]["account_type"] | null
        }
        Relationships: [
          {
            foreignKeyName: "accounts_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      v_monthly_category_totals: {
        Row: {
          currency: string | null
          category_color: string | null
          category_icon: string | null
          category_id: string | null
          category_name_ar: string | null
          category_name_en: string | null
          entries: number | null
          household_id: string | null
          month: string | null
          total: number | null
          type: Database["public"]["Enums"]["txn_type"] | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      v_monthly_summary: {
        Row: {
          currency: string | null
          expense: number | null
          household_id: string | null
          income: number | null
          month: string | null
          net: number | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      v_transactions: {
        Row: {
          currency: string | null
          to_amount: number | null
          account_id: string | null
          account_name_ar: string | null
          account_name_en: string | null
          amount: number | null
          category_color: string | null
          category_icon: string | null
          category_id: string | null
          category_name_ar: string | null
          category_name_en: string | null
          created_at: string | null
          created_by: string | null
          household_id: string | null
          id: string | null
          item_id: string | null
          item_name_ar: string | null
          item_name_en: string | null
          note: string | null
          occurred_on: string | null
          photo_path: string | null
          subcategory_id: string | null
          subcategory_name_ar: string | null
          subcategory_name_en: string | null
          to_account_id: string | null
          type: Database["public"]["Enums"]["txn_type"] | null
          updated_at: string | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_household_id_account_id_fkey"
            columns: ["household_id", "account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["household_id", "id"]
          },
          {
            foreignKeyName: "transactions_household_id_account_id_fkey"
            columns: ["household_id", "account_id"]
            isOneToOne: false
            referencedRelation: "v_account_balances"
            referencedColumns: ["household_id", "account_id"]
          },
          {
            foreignKeyName: "transactions_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_household_id_item_id_fkey"
            columns: ["household_id", "item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["household_id", "id"]
          },
          {
            foreignKeyName: "transactions_household_id_to_account_id_fkey"
            columns: ["household_id", "to_account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["household_id", "id"]
          },
          {
            foreignKeyName: "transactions_household_id_to_account_id_fkey"
            columns: ["household_id", "to_account_id"]
            isOneToOne: false
            referencedRelation: "v_account_balances"
            referencedColumns: ["household_id", "account_id"]
          },
        ]
      }
    }
    Functions: {
      add_member: {
        Args: { p_display_name: string; p_email: string }
        Returns: undefined
      }
      clear_sample_data: { Args: never; Returns: undefined }
      create_family: {
        Args: {
          p_currencies?: string[]
          p_display_name: string
          p_locale?: string
          p_name: string
        }
        Returns: string
      }
      create_household: {
        Args: { p_display_name: string; p_locale?: string; p_name: string }
        Returns: string
      }
      is_member: { Args: { hid: string }; Returns: boolean }
      keepalive: { Args: never; Returns: string }
      restore_sample_data: { Args: never; Returns: undefined }
      operator_families: {
        Args: never
        Returns: {
          admin_user_id: string
          created_at: string
          currencies: string[]
          entries: number
          household_id: string
          last_entry_at: string
          members: number
          name: string
          status: string
          wallets: number
        }[]
      }
      seed_budgets: { Args: { hid: string }; Returns: undefined }
      seed_corrections: { Args: { hid: string }; Returns: undefined }
      seed_defaults: { Args: { hid: string }; Returns: undefined }
      set_family_status: {
        Args: { p_household_id: string; p_status: string }
        Returns: undefined
      }
      invite_family: {
        Args: { p_email: string; p_friend_name: string }
        Returns: string
      }
      set_household_currencies: {
        Args: { p_currencies: string[] }
        Returns: undefined
      }
      valid_currencies: { Args: { c: string[] }; Returns: boolean }
    }
    Enums: {
      account_type: "cash" | "bank" | "card" | "wallet"
      category_kind: "expense" | "income"
      txn_type: "expense" | "income" | "transfer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      account_type: ["cash", "bank", "card", "wallet"],
      category_kind: ["expense", "income"],
      txn_type: ["expense", "income", "transfer"],
    },
  },
} as const
