import * as React from 'react';
import {
  Apple,
  ArrowLeftRight,
  Baby,
  Banknote,
  Book,
  Briefcase,
  Building2,
  Bus,
  Car,
  CircleDot,
  Coffee,
  Coins,
  Droplet,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gift,
  GraduationCap,
  Hammer,
  HeartPulse,
  House,
  Landmark,
  Music,
  Pizza,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Smile,
  Sparkles,
  Tag,
  Train,
  Tv,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  house: House,
  'shopping-basket': ShoppingBasket,
  'shopping-bag': ShoppingBag,
  car: Car,
  fuel: Fuel,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  sparkles: Sparkles,
  shirt: Shirt,
  smile: Smile,
  receipt: Receipt,
  banknote: Banknote,
  'building-2': Building2,
  'arrow-left-right': ArrowLeftRight,
  briefcase: Briefcase,
  coins: Coins,
  utensils: Utensils,
  wallet: Wallet,
  tag: Tag,
  users: Users,
  baby: Baby,
  gift: Gift,
  smartphone: Smartphone,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  wifi: Wifi,
  bus: Bus,
  train: Train,
  plane: Plane,
  coffee: Coffee,
  pizza: Pizza,
  apple: Apple,
  dumbbell: Dumbbell,
  film: Film,
  music: Music,
  tv: Tv,
  book: Book,
  wrench: Wrench,
  hammer: Hammer,
  landmark: Landmark,
};

export interface CategoryIconProps extends Omit<React.ComponentProps<'svg'>, 'name'> {
  name?: string | null;
  className?: string;
}

export function CategoryIcon({ name, className = 'size-6', ...props }: CategoryIconProps) {
  const IconComponent = (name && ICON_MAP[name.toLowerCase()]) || CircleDot;
  return <IconComponent className={className} {...props} />;
}
